name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install dependencies
      run: npm install

    - name: Build and compress CSS
      run: |
        npm run build
        npm run compress

    - name: Copy compiled CSS to dist
      run: |
        cp -r feedly* local-overrides* dist

    - name: Checkout dist branch
      uses: actions/checkout@v2
      with:
        ref: dist
        fetch-depth: 0

    - name: Copy compiled CSS to root
      run: cp -r dist/* .

    - name: Commit and push changes to dist branch
      run: |
        git config --global user.email "levito82@gmail.com"
        git config --global user.name "Veit Lehmann"
        git add .
        git commit -m "build css"
        git push origin dist
