name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Get submodule cache
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: tt-rss
        key: submodule-${{ hashFiles('.git/modules/tt-rss') }}

    - name: Install dependencies
      run: npm install

    - name: Cache submodule
      uses: actions/cache/save@v3
      with:
        path: tt-rss
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    # - name: Build and compress CSS
    #   run: npm run dist

    # - name: Checkout dist branch
    #   uses: actions/checkout@v3
    #   with:
    #     ref: dist
    #     clean: false

    # - name: Copy compiled CSS to root
    #   run: rsync -a dist/ .

    # - name: Commit and push changes to dist branch
    #   run: |
    #     git config --global user.email "levito82@gmail.com"
    #     git config --global user.name "Veit Lehmann"
    #     if [[ $(git status --porcelain) ]]; then
    #       git add .
    #       git commit -m "build css"
    #       git push origin dist
    #     else
    #       echo "No changes to commit"
    #     fi

    # - name: Switch back to main branch
    #   uses: actions/checkout@v3
    #   with:
    #     ref: main
