name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install dependencies
      run: npm install

    - name: Build and compress CSS
      run: npm run dist

    - name: Checkout dist branch
      uses: actions/checkout@v3
      with:
        ref: dist
        clean: false

    - name: Copy compiled CSS to root
      run: rsync -a dist/ .

    - name: Commit and push changes to dist branch
      run: |
        git config --global user.email "levito82@gmail.com"
        git config --global user.name "Veit Lehmann"
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "build css"
          git push origin dist
        else
          echo "No changes to commit"
        fi
