name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: npm install

    - name: Build and compress CSS
      run: npm run dist

    - name: Checkout dist branch
      uses: actions/checkout@v3
      with:
        ref: dist
        clean: false

    - name: Copy compiled CSS to root
      run: rsync -a dist/ .

    - name: Commit and push changes to dist branch
      run: |
        git config --global user.email "levito82@gmail.com"
        git config --global user.name "Veit Lehmann"
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "build css"
          git push origin dist
        else
          echo "No changes to commit"
        fi

    - name: Switch back to main branch
      uses: actions/checkout@v3
      with:
        ref: main
